################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 3 - Alpha",
		"License :: OSI Approved :: Apache Software License",
	],
	description = "This python module parses (and produces) vCard data as provided in vcf files.",
	download_url = "https://github.com/jkpubsrc/python-module-jk-vcard/tarball/0.2020.9.21",
	include_package_data = False,
	install_requires = [
		"jk_typing",
		"jk_version",
		"jk_utils",
	],
	keywords = [
		"vcard",
		"vcf",
	],
	license = "Apache 2.0",
	name = "jk_vcard",
	packages = [
		"jk_vcard",
	],
	url = "https://github.com/jkpubsrc/python-module-jk-vcard",
	version = "0.2020.9.21.1",
	zip_safe = False,
	long_description = readme(),
	long_description_content_type="text/markdown",
)
